add login, swagger config and mapper
SoftwareEngineeringBanking/InternetBanking pull request #4
Opened 2020-04-06 03:33 UTC by matheussla

2020-04-13 10:49 UTC, xmacedo-zz requested changes

2020-04-13 10:49 UTC, xmacedo commented on .idea/.gitignore
> +/workspace.xml
Remover arquivos do .idea (IntelliJ)

2020-04-13 10:49 UTC, xmacedo commented on .idea/InternetBanking.iml
> +</module>
Remover arquivos do .idea (IntelliJ)

2020-04-13 10:49 UTC, xmacedo commented on .idea/misc.xml
> +</project>
Remover arquivos do .idea (IntelliJ)

2020-04-13 10:49 UTC, xmacedo commented on .idea/modules.xml
> +</project>
Remover arquivos do .idea (IntelliJ)

2020-04-13 10:49 UTC, xmacedo commented on .idea/vcs.xml
> +</project>
Remover arquivos do .idea (IntelliJ)

2020-04-13 20:17 UTC, leomiranda1995 approved these changes

2020-04-17 03:47 UTC, leomiranda1995 approved these changes

2020-05-14 23:02 UTC, alexandre-malabarba approved these changes

2020-05-14 23:02 UTC, alexandre-malabarba approved these changes

2020-05-14 23:04 UTC, alexandre-malabarba approved these changes

2020-05-14 23:26 UTC, felipewurch approved these changes

2020-05-16 16:18 UTC, merged